<a href="https://colab.research.google.com/github/KiaraSN/Aprendendo-Pytorch/blob/main/Pytorch_1_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
# matriz de ceros, 5 filas y 3 columnas

x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# tensor con valores aleatorios
# ess é uma matriz tridimensional, 5 matriz de 3 filas e 2 colunas

x = torch.randn(5, 3, 2)
x

tensor([[[-1.2776, -1.1086],
         [ 1.8318,  1.9095],
         [ 0.4107, -0.9806]],

        [[-0.8762,  1.1157],
         [ 1.3077,  2.0498],
         [-1.1894, -0.8696]],

        [[ 1.9016, -0.6736],
         [ 1.2341, -0.6871],
         [-0.0110, -0.2791]],

        [[ 1.1723,  0.0166],
         [-1.2438,  0.1167],
         [-1.4670, -0.2188]],

        [[ 0.6230, -0.0370],
         [ 0.9714, -1.5327],
         [-0.4415, -1.7512]]])

In [ ]:
# tensor a partir de lista

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
import numpy as np

# tensor a partir de array

a = np.array([[1, 2, 3], [4, 5, 6]])
x = torch.from_numpy(a)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# operaciones

x = torch.randn(3, 3)
y = torch.randn(3, 3)
z = torch.randn(5, 6)

x, y, z

(tensor([[ 0.2387, -0.3082,  0.0799],
         [ 1.5051,  2.7477,  0.5289],
         [-2.0817, -1.4219,  0.5676]]),
 tensor([[-1.7326,  1.1509, -0.0073],
         [-0.7649,  0.6480, -2.6486],
         [-1.0900, -0.7586,  1.7505]]),
 tensor([[ 2.2538,  0.0078,  0.9313,  0.4895,  0.0407, -0.3592],
         [ 0.9721, -0.6490,  0.4941,  0.3460,  0.9124, -0.0605],
         [-1.7248,  0.2034,  0.8691,  1.3876,  0.4063, -1.0742],
         [ 0.2848,  0.2678, -0.1669,  0.4006, -0.5612,  1.4833],
         [ 2.1129,  0.3225, -0.3107, -1.8369,  0.0423, -0.5822]]))

In [ ]:
x - y



tensor([[ 1.9713, -1.4590,  0.0872],
        [ 2.2700,  2.0996,  3.1775],
        [-0.9917, -0.6633, -1.1830]])

In [ ]:
# indexar

#por filas, exemplo da primeira fila (lembrando q começa por 0)

x[0]

tensor([ 0.2387, -0.3082,  0.0799])

In [ ]:
[] # primeira fila, primiera coluna

x[0, 0]

tensor(0.2387)

In [ ]:
# o mesmo com : prga tudo daquela dimensão

z[0, :]

tensor([ 2.2538,  0.0078,  0.9313,  0.4895,  0.0407, -0.3592])

In [ ]:
# picado, so as parte

x[:-1, 1:]

# nesse caso vai imprimir todas as filas, exceto a 1, e todas as colunas, exceto a primiera

tensor([[-0.3082,  0.0799],
        [ 2.7477,  0.5289]])

In [ ]:
### añadimos una dimension extra

x.view(1, 3, 3).shape
x

tensor([[ 0.2387, -0.3082,  0.0799],
        [ 1.5051,  2.7477,  0.5289],
        [-2.0817, -1.4219,  0.5676]])

In [ ]:
x = torch.tensor(1., requires_grad=True)
y = torch.tensor(2., requires_grad=True)
p = x + y

z = torch.tensor(3., requires_grad=True)
g = p * z

In [ ]:
g.backward()

In [ ]:
x.grad

tensor(3.)

In [35]:
import torch
print(torch.cuda.is_available())  # Deve retornar True
print(torch.cuda.get_device_name(0))  # Nome da GPU disponível


False


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [36]:
torch.cuda.is_available()


False

In [ ]:
# comprobar que podemos usar GPU

torch.cuda.is_available()

False

In [ ]:
# aqui não estava ativada a GPU e se instalar vai apagar, então continuo na parte 2 outro arquivo. Pode ter outras soluções mas não sei ainda.